from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, update, insert
from sqlalchemy.orm import selectinload
from typing import List, Optional, Dict, Any
from datetime import datetime
import uuid
import structlog

from app.models.ai import AIJob, AIContent
from app.schemas.ai import AIJobCreate, AIJobResponse, AIContentResponse

logger = structlog.get_logger()

class AIService:
    def __init__(self, db: AsyncSession):
        self.db = db
    
    async def create_job(self, job_data: AIJobCreate, user_id: str) -> Optional[AIJob]:
        """Create a new AI job"""
        try:
            job = AIJob(
                job_type=job_data.job_type,
                provider=job_data.provider,
                payload=job_data.payload,
                priority=job_data.priority or 1
            )
            
            self.db.add(job)
            await self.db.commit()
            await self.db.refresh(job)
            
            return job
        except Exception as e:
            await self.db.rollback()
            logger.error(f"Error creating AI job: {e}")
            return None
    
    async def get_user_jobs(
        self, 
        user_id: str,
        job_type: Optional[str] = None, 
        status: Optional[str] = None,
        skip: int = 0, 
        limit: int = 100
    ) -> List[AIJob]:
        """Get user's AI jobs with filtering"""
        try:
            # Note: In a real implementation, you'd filter by user_id
            # For now, we'll return all jobs
            stmt = select(AIJob)
            
            if job_type:
                stmt = stmt.where(AIJob.job_type == job_type)
            if status:
                stmt = stmt.where(AIJob.status == status)
            
            stmt = stmt.offset(skip).limit(limit).order_by(AIJob.created_at.desc())
            result = await self.db.execute(stmt)
            return result.scalars().all()
        except Exception as e:
            logger.error(f"Error getting AI jobs: {e}")
            return []
    
    async def get_job_by_id(self, job_id: str) -> Optional[AIJob]:
        """Get AI job by ID"""
        try:
            stmt = select(AIJob).where(AIJob.id == job_id)
            result = await self.db.execute(stmt)
            return result.scalar_one_or_none()
        except Exception as e:
            logger.error(f"Error getting AI job by ID: {e}")
            return None
    
    async def cancel_job(self, job_id: str, user_id: str) -> bool:
        """Cancel an AI job"""
        try:
            # Note: In a real implementation, you'd verify user ownership
            stmt = update(AIJob).where(AIJob.id == job_id).values(
                status="cancelled",
                updated_at=datetime.utcnow()
            )
            await self.db.execute(stmt)
            await self.db.commit()
            return True
        except Exception as e:
            await self.db.rollback()
            logger.error(f"Error cancelling AI job: {e}")
            return False
    
    async def get_job_content(self, job_id: str, user_id: str) -> List[AIContent]:
        """Get content generated by an AI job"""
        try:
            # Note: In a real implementation, you'd verify user ownership
            stmt = select(AIContent).where(AIContent.ai_job_id == job_id)
            result = await self.db.execute(stmt)
            return result.scalars().all()
        except Exception as e:
            logger.error(f"Error getting AI job content: {e}")
            return []
    
    async def generate_questions(
        self, 
        exam_id: str, 
        topic_ids: List[str], 
        num_questions: int, 
        difficulty_mix: Optional[Dict[str, float]] = None,
        user_id: str = None
    ) -> Optional[AIJob]:
        """Generate questions using AI"""
        try:
            payload = {
                "exam_id": exam_id,
                "topic_ids": topic_ids,
                "num_questions": num_questions,
                "difficulty_mix": difficulty_mix or {"easy": 0.3, "medium": 0.5, "hard": 0.2}
            }
            
            job_data = AIJobCreate(
                job_type="generate_questions",
                provider="openai",
                payload=payload,
                priority=1
            )
            
            return await self.create_job(job_data, user_id)
        except Exception as e:
            logger.error(f"Error creating question generation job: {e}")
            return None
