from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List, Optional
import structlog

from app.core.database import get_db
from app.schemas.ai import AIJobCreate, AIJobResponse, AIContentResponse
from app.core.dependencies import get_current_user, get_current_admin_user
from app.services.ai import AIService

logger = structlog.get_logger()

router = APIRouter()

@router.post("/jobs", response_model=AIJobResponse, status_code=status.HTTP_201_CREATED)
async def create_ai_job(
    job_data: AIJobCreate,
    current_user = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Create a new AI job"""
    try:
        ai_service = AIService(db)
        job = await ai_service.create_job(job_data, current_user.id)
        
        logger.info(f"AI job created successfully: {job.id}")
        return job
    except Exception as e:
        logger.error(f"Create AI job error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Internal server error"
        )

@router.get("/jobs", response_model=List[AIJobResponse])
async def get_ai_jobs(
    job_type: Optional[str] = Query(None),
    status: Optional[str] = Query(None),
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    current_user = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Get AI jobs with filtering"""
    try:
        ai_service = AIService(db)
        jobs = await ai_service.get_user_jobs(
            user_id=current_user.id,
            job_type=job_type,
            status=status,
            skip=skip,
            limit=limit
        )
        return jobs
    except Exception as e:
        logger.error(f"Get AI jobs error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Internal server error"
        )

@router.get("/jobs/{job_id}", response_model=AIJobResponse)
async def get_ai_job(
    job_id: str,
    current_user = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Get AI job by ID"""
    try:
        ai_service = AIService(db)
        job = await ai_service.get_job_by_id(job_id)
        
        if not job:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="AI job not found"
            )
        
        # Check if user owns this job
        if str(job.user_id) != str(current_user.id):
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Not enough permissions"
            )
        
        return job
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Get AI job error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Internal server error"
        )

@router.post("/jobs/{job_id}/cancel")
async def cancel_ai_job(
    job_id: str,
    current_user = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Cancel an AI job"""
    try:
        ai_service = AIService(db)
        await ai_service.cancel_job(job_id, current_user.id)
        
        logger.info(f"AI job cancelled successfully: {job_id}")
        return {"message": "AI job cancelled successfully"}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Cancel AI job error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Internal server error"
        )

@router.get("/jobs/{job_id}/content", response_model=List[AIContentResponse])
async def get_ai_job_content(
    job_id: str,
    current_user = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Get content generated by an AI job"""
    try:
        ai_service = AIService(db)
        content = await ai_service.get_job_content(job_id, current_user.id)
        
        return content
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Get AI job content error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Internal server error"
        )

@router.post("/generate-questions")
async def generate_questions(
    exam_id: str,
    topic_ids: List[str],
    num_questions: int = Query(10, ge=1, le=100),
    difficulty_mix: Optional[dict] = None,
    current_user = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Generate questions using AI"""
    try:
        ai_service = AIService(db)
        job = await ai_service.generate_questions(
            exam_id=exam_id,
            topic_ids=topic_ids,
            num_questions=num_questions,
            difficulty_mix=difficulty_mix,
            user_id=current_user.id
        )
        
        logger.info(f"Question generation job created: {job.id}")
        return {"job_id": str(job.id), "status": job.status}
    except Exception as e:
        logger.error(f"Generate questions error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Internal server error"
        )
